//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВКР.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Зміст_реалізації
    {
        public int ID_зміст_реал { get; set; }
        public Nullable<int> ID_покупки { get; set; }
        public Nullable<int> Кількість { get; set; }
        public Nullable<int> ID_товару { get; set; }
    
        public virtual Реалізація Реалізація { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
