//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВКР.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Реалізація
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Реалізація()
        {
            this.Зміст_реалізації = new HashSet<Зміст_реалізації>();
        }
    
        public int ID_покупки { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> ID_магазину { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Зміст_реалізації> Зміст_реалізації { get; set; }
        public virtual Магазини Магазини { get; set; }
    }
}
