//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВКР.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Зміст_реалізації = new HashSet<Зміст_реалізації>();
        }
    
        public int ID_товару { get; set; }
        public string Назва { get; set; }
        public Nullable<int> Ціна { get; set; }
        public string Розмір { get; set; }
        public Nullable<int> ID_товарної_групи { get; set; }
        public Nullable<int> ID_пори_року { get; set; }
        public Nullable<int> ID_категорії { get; set; }
        public Nullable<int> ID_матеріалу { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Зміст_реалізації> Зміст_реалізації { get; set; }
        public virtual Матеріали Матеріали { get; set; }
        public virtual Товар_по_категоріям Товар_по_категоріям { get; set; }
        public virtual Товар_по_порам_року Товар_по_порам_року { get; set; }
        public virtual Товарна_група Товарна_група { get; set; }
    }
}
